export * from "./algorithm/index"
export * from "./data/index"
export * from "./events/index"
export * from "./extension/index"
export * from "./geometry/index"
export * from "./html/index"
export * from "./transform/index"
export * from "./utils/index"

export const name = "Coopa"
